### ISSUE TITLE
[linq2db] InvalidCastException reading value of Time parameter

### ISSUE THREAD

**Issue by MaceWindu** [DataAction/AdoNetCore.AseClient#48]
Error: `Specified cast is not valid. Parameter: @p. From: DateTime to: TimeSpan`

test code:
```cs
var time = new TimeSpan(12, 12, 12);
Assert.That(conn.Execute<TimeSpan> ("SELECT @p", DataParameter.Time  ("p", time)),              Is.EqualTo(time));
```

stack:
```
SET     @p = '1900-01-01 12:12:12'

SELECT @p

DataConnection: Error
Exception: System.InvalidCastException
Message  : Specified cast is not valid. Parameter: @p. From: DateTime to: TimeSpan
   at AdoNetCore.AseClient.Internal.ValueWriter.Cast[T](Object value, FormatItem format)
   at AdoNetCore.AseClient.Internal.ValueWriter.Write(Object value, Stream stream, FormatItem format, Encoding enc)
   at AdoNetCore.AseClient.Token.ParametersToken.Write(Stream stream, DbEnvironment env)
   at AdoNetCore.AseClient.Packet.NormalPacket.Write(Stream stream, DbEnvironment env)
   at AdoNetCore.AseClient.Internal.RegularSocket.SendPacket(IPacket packet, DbEnvironment env)
   at AdoNetCore.AseClient.Internal.InternalConnection.SendPacket(IPacket packet)
   at AdoNetCore.AseClient.Internal.InternalConnection.InternalExecuteAsync(AseCommand command, AseTransaction transaction, TaskCompletionSource`1 rowsAffectedSource, TaskCompletionSource`1 readerSource, CommandBehavior behavior)
--- End of stack trace from previous location where exception was thrown ---
   at AdoNetCore.AseClient.Internal.InternalConnection.ExecuteReader(CommandBehavior behavior, AseCommand command, AseTransaction transaction)
   at AdoNetCore.AseClient.AseCommand.ExecuteReader(CommandBehavior behavior)
   at AdoNetCore.AseClient.AseCommand.ExecuteDbDataReader(CommandBehavior behavior)
   at System.Data.Common.DbCommand.System.Data.IDbCommand.ExecuteReader(CommandBehavior behavior)
   at LinqToDB.Data.DataConnection.ExecuteReader(CommandBehavior commandBehavior) in c:\GitHub\linq2db.work\Source\LinqToDB\Data\DataConnection.cs:line 1138
```

linq2db test: `SybaseTests.TestTimeSpan`

**Comment by MaceWindu** [comment]
Note that conversion to DateTime is done on our side
```
case DataType.Time       :
					if (value is TimeSpan) value = new DateTime(1900, 1, 1) + (TimeSpan)value;
					break;
```
I'm not the author of that conversion, but I suspect it was probably the only working approach with native provider.

**Comment by senseibaka** [comment]
The reference (SAP) driver does not have native support for `System.TimeSpan`, so it outputs and expects to receive `System.DateTime` (hence the conversion code in `linq2db`).

Whereas, our driver expects to use `System.TimeSpan`, but is being passed a `System.DateTime`... obviously, if we intend to be usable as a drop-in replacement we should fix this.

So, we will fix this by:
* Accepting `System.DateTime` for a `time` parameter, and converting appropriately
  * We will still accept `System.TimeSpan` as input
* Emitting `System.DateTime` for a `time` result
  * Our implementation of `AseDataReader` already comes with a `public TimeSpan GetTimeSpan(int i)` method, something the reference driver does not provide.

**Comment by MaceWindu** [comment]
Partially fixed, native provider returns DateTime as 1-1-0001, not 1-1-1900

**Comment by MaceWindu** [comment]
I will fill new issue
